bunny:
  master:
    host: 192.168.3.137
    port: 3306
    database: auth_admin
    username: root
    password: "123456"
  connect:
    url: jdbc:sqlite::resource:database.sqlite
    username: root
    password: "123456"